#! /usr/bin/env python
# encoding: utf-8

from waflib import Utils
import os

top = '.'
PROJECT_NAME = 'bullet'

def options(opt):
	# stub
	return

def configure(conf):
	return

def build(bld):
	source = bld.path.ant_glob('**/*.cpp')

	includes = [
		'.'
	]

	defines = []

	libs = []

	install_path = bld.env.LIBDIR

	bld.stlib(
		source   = source,
		target   = PROJECT_NAME,
		name     = PROJECT_NAME,
		features = 'c cxx',
		includes = includes,
		defines  = defines,
		use      = libs,
		subsystem = bld.env.MSVC_SUBSYSTEM,
		idx      = bld.get_taskgen_count()
	)

