#! /usr/bin/env python
# encoding: utf-8

from waflib import Utils
import os

top = '.'
PROJECT_NAME = 'lua'

def options(opt):
	return

def configure(conf):
	if conf.env.DEST_OS in ["linux", "android", "freebsd", "osx"]:
		conf.define( "LUA_USE_LINUX", 1 )
	return

def build(bld):
	source = [
		"lua-5.1.5/src/lapi.c",
		"lua-5.1.5/src/lauxlib.c",
		"lua-5.1.5/src/lbaselib.c",
		"lua-5.1.5/src/lcode.c",
		"lua-5.1.5/src/ldblib.c",
		"lua-5.1.5/src/ldebug.c",
		"lua-5.1.5/src/ldo.c",
		"lua-5.1.5/src/ldump.c",
		"lua-5.1.5/src/lfunc.c",
		"lua-5.1.5/src/lgc.c",
		"lua-5.1.5/src/linit.c",
		"lua-5.1.5/src/liolib.c",
		"lua-5.1.5/src/llex.c",
		"lua-5.1.5/src/lmathlib.c",
		"lua-5.1.5/src/lmem.c",
		"lua-5.1.5/src/loadlib.c",
		"lua-5.1.5/src/lobject.c",
		"lua-5.1.5/src/lopcodes.c",
		"lua-5.1.5/src/loslib.c",
		"lua-5.1.5/src/lparser.c",
		"lua-5.1.5/src/lstate.c",
		"lua-5.1.5/src/lstring.c",
		"lua-5.1.5/src/lstrlib.c",
		"lua-5.1.5/src/ltable.c",
		"lua-5.1.5/src/ltable.c",
		"lua-5.1.5/src/ltablib.c",
		"lua-5.1.5/src/ltm.c",
		"lua-5.1.5/src/lundump.c",
		"lua-5.1.5/src/lvm.c",
		"lua-5.1.5/src/lzio.c",
		"lua-5.1.5/src/print.c"
	]

	includes = [
		'.',
		'./lua-5.1.5/src',
		'../public',
		'../common'
	]

	defines = []

	libs = []

	bld.stlib(
		source   = source,
		target   = PROJECT_NAME,
		name     = PROJECT_NAME,
		features = 'c cxx',
		includes = includes,
		defines  = defines,
		use      = libs,
		subsystem = bld.env.MSVC_SUBSYSTEM,
		idx      = bld.get_taskgen_count()
	)

